name: deezer-desktop
base: core24
version: '7.1.20'
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
summary: Online music streaming service
description: |
    An unofficial linux port of the deezer desktop application.
    Access all of your favorite music, and save them offline for later!
grade: stable
confinement: strict
icon: dev.aunetx.deezer.svg

apps:
  deezer-desktop:
    command: opt/deezer-desktop/deezer-desktop --no-sandbox
    desktop: usr/share/applications/deezer-desktop.desktop
    common-id: dev.aunetx.deezer
    extensions: [gnome]
    plugs:
      - audio-playback
      - unity7
      - network
      - network-bind
      - screen-inhibit-control
      - home
      - removable-media

plugs:
  shared-memory:
    private: true

parts:
  deezer-linux:
    plugin: dump
    source:
      - on amd64: https://github.com/aunetx/deezer-linux/releases/download/v$SNAPCRAFT_PROJECT_VERSION/deezer-desktop_$SNAPCRAFT_PROJECT_VERSION_amd64.deb
      - on arm64: https://github.com/aunetx/deezer-linux/releases/download/v$SNAPCRAFT_PROJECT_VERSION/deezer-desktop_$SNAPCRAFT_PROJECT_VERSION_arm64.deb
    prime:
      - usr
      - opt
